Convert to using arrays for command building Quote as many variables likely to hold paths as possible Don't execute output of fsl_sub --has_coprocessor='cuda'!

diff --git a/CUDA/bedpostx_gpu b/CUDA/bedpostx_gpu
--- a/CUDA/bedpostx_gpu
+++ b/CUDA/bedpostx_gpu
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash
 
 #   Copyright (C) 2004 University of Oxford
 #
@@ -44,16 +44,16 @@ nparts=0
 if [ $njobs -eq 1 ]; then
 #1 part (GPU) and several subparts
 #voxels processed in each subpart are 12800 or more if the last one is less than 6400 (1 part less)
-	nparts=\$(($nvox/12800))
-	if [ \$nparts%12800 != 0 ];then
-		nparts=\$((\$nparts + 1))
-	fi
-	last_part=\$(($nvox-(((\$nparts-1))*12800)))
-	if [ \$last_part -lt 6400 ];then
-		nparts=\$((\$nparts - 1))
-	fi
+    nparts=\$(($nvox/12800))
+    if [ \$nparts%12800 != 0 ];then
+        nparts=\$((\$nparts + 1))
+    fi
+    last_part=\$(($nvox-(((\$nparts-1))*12800)))
+    if [ \$last_part -lt 6400 ];then
+        nparts=\$((\$nparts - 1))
+    fi
 else
-	nparts=$njobs
+    nparts=$njobs
 fi
 
 echo
@@ -88,7 +88,7 @@ while [ \$finished -eq 0 ] ; do
     if [ -f ${subjdir}.bedpostX/xfms/eye.mat ] ; then
         finished=1
         echo "All parts processed"
-	exit
+    exit
     fi
     if [ ! \$havedad -gt 0 ]; then
        exit 0
@@ -99,31 +99,31 @@ while [ \$finished -eq 0 ] ; do
     sleep 50;
 done
 EOM
-    chmod +x ${subjdir}.bedpostX/monitor
+    chmod +x "${subjdir}.bedpostX/monitor"
 }
 
 make_absolute(){
     dir=$1;
-    if [ -d ${dir} ]; then
-	OLDWD=`pwd`
-	cd ${dir}
-	dir_all=`pwd`
-	cd $OLDWD
+    if [ -d "${dir}" ]; then
+        OLDWD=$(pwd)
+        cd "${dir}"
+        dir_all=$(pwd)
+        cd "$OLDWD"
     else
-	dir_all=${dir}
+        dir_all="${dir}"
     fi
-    echo ${dir_all}
+    echo "${dir_all}"
 }
 
 [ "$1" = "" ] && Usage
 
-subjdir=`make_absolute $1`
-subjdir=`echo $subjdir | sed 's/\/$/$/g'`
+subjdir=$(make_absolute "$1")
+subjdir=$(echo "$subjdir" | sed 's/\/$/$/g')
 
 echo "---------------------------------------------"
 echo "------------ BedpostX GPU Version -----------"
 echo "---------------------------------------------"
-echo subjectdir is $subjdir
+echo "subjectdir is $subjdir"
 
 #parse option arguments
 qsys=0
@@ -152,13 +152,13 @@ do
       -s) sampleevery=$2;shift;;
       -model) model=$2;shift;;
       -g) gflag=1;;
-      *) other=$other" "$1;;
+      *) other=("$other" "$1");;
   esac
   shift
 done
 
-if [ $qsys -eq 0 ] && [ -z "$queue" ]; then
-    if $("$FSLDIR/bin/fsl_sub" --has_coprocessor='cuda' > /dev/null); then
+if [ "$qsys" -eq 0 ] && [ -z "$queue" ]; then
+    if "$FSLDIR/bin/fsl_sub" --has_coprocessor='cuda' > /dev/null; then
         queue="--coprocessor=cuda"
     else
         echo "No GPU configured/found" >&2
@@ -166,168 +166,173 @@ if [ $qsys -eq 0 ] && [ -z "$queue" ]; then
     fi
 fi
 
-opts="--nf=$nfibres --fudge=$fudge --bi=$burnin --nj=$njumps --se=$sampleevery --model=$model"
-defopts="--cnonlinear"
-opts="$opts $defopts $other"
+opts=("--nf=$nfibres" "--fudge=$fudge" "--bi=$burnin" "--nj=$njumps" "--se=$sampleevery" "--model=$model")
+defopts=("--cnonlinear")
+opts=("${opts[@]}" "${defopts[@]}" "${other[@]}")
 
 #check that all required files exist
 
-if [ ! -d $subjdir ]; then
-	echo "subject directory $1 not found" >&2
-	exit 1
+if [ ! -d "$subjdir" ]; then
+    echo "subject directory $1 not found" >&2
+    exit 1
 fi
 
-if [ ! -e ${subjdir}/bvecs ]; then
-    if [ -e ${subjdir}/bvecs.txt ]; then
-	mv ${subjdir}/bvecs.txt ${subjdir}/bvecs
+if [ ! -e "${subjdir}/bvecs" ]; then
+    if [ -e "${subjdir}/bvecs.txt" ]; then
+        mv "${subjdir}/bvecs.txt" "${subjdir}/bvecs"
     else
-	echo "${subjdir}/bvecs not found" >&2
-	exit 1
+        echo "${subjdir}/bvecs not found" >&2
+        exit 1
     fi
 fi
 
-if [ ! -e ${subjdir}/bvals ]; then
-    if [ -e ${subjdir}/bvals.txt ]; then
-	mv ${subjdir}/bvals.txt ${subjdir}/bvals
+if [ ! -e "${subjdir}/bvals" ]; then
+    if [ -e "${subjdir}/bvals.txt" ]; then
+        mv "${subjdir}/bvals.txt" "${subjdir}/bvals"
     else
-	echo "${subjdir}/bvals not found" >&2
-	exit 1
+        echo "${subjdir}/bvals not found" >&2
+        exit 1
     fi
 fi
 
-if [ `${FSLDIR}/bin/imtest ${subjdir}/data` -eq 0 ]; then
-	echo "${subjdir}/data not found" >&2
-	exit 1
+if [ $("${FSLDIR}/bin/imtest" "${subjdir}/data") -eq 0 ]; then
+    echo "${subjdir}/data not found" >&2
+    exit 1
 fi
 
 if [ ${gflag} -eq 1 ]; then
-    if [ `${FSLDIR}/bin/imtest ${subjdir}/grad_dev` -eq 0 ]; then
-	echo "${subjdir}/grad_dev not found" >&2
-	exit 1
+    if [ $("${FSLDIR}/bin/imtest" "${subjdir}/grad_dev") -eq 0 ]; then
+        echo "${subjdir}/grad_dev not found" >&2
+        exit 1
     fi
 fi
 
-if [ `${FSLDIR}/bin/imtest ${subjdir}/nodif_brain_mask` -eq 0 ]; then
-	echo "${subjdir}/nodif_brain_mask not found" >&2
-	exit 1
+if [ $("${FSLDIR}/bin/imtest" "${subjdir}/nodif_brain_mask") -eq 0 ]; then
+    echo "${subjdir}/nodif_brain_mask not found" >&2
+    exit 1
 fi
 
-if [ -e ${subjdir}.bedpostX/xfms/eye.mat ]; then
-	echo "${subjdir} has already been processed: ${subjdir}.bedpostX." >&2
-	echo "Delete or rename ${subjdir}.bedpostX before repeating the process." >&2
-	exit 1
+if [ -e "${subjdir}.bedpostX/xfms/eye.mat" ]; then
+    echo "${subjdir} has already been processed: ${subjdir}.bedpostX." >&2
+    echo "Delete or rename ${subjdir}.bedpostX before repeating the process." >&2
+    exit 1
 fi
 
-echo Making bedpostx directory structure
+echo "Making bedpostx directory structure"
 
-mkdir -p ${subjdir}.bedpostX/
-mkdir -p ${subjdir}.bedpostX/diff_parts
-mkdir -p ${subjdir}.bedpostX/logs
-mkdir -p ${subjdir}.bedpostX/logs/logs_gpu
-mkdir -p ${subjdir}.bedpostX/logs/monitor
+mkdir -p "${subjdir}.bedpostX/"
+mkdir -p "${subjdir}.bedpostX/diff_parts"
+mkdir -p "${subjdir}.bedpostX/logs"
+mkdir -p "${subjdir}.bedpostX/logs/logs_gpu"
+mkdir -p "${subjdir}.bedpostX/logs/monitor"
 rm -f "${subjdir}".bedpostX/logs/monitor/*
-mkdir -p ${subjdir}.bedpostX/xfms
+mkdir -p "${subjdir}.bedpostX/xfms"
 
-echo Copying files to bedpost directory
+echo "Copying files to bedpost directory"
 
-cp ${subjdir}/bvecs ${subjdir}/bvals ${subjdir}.bedpostX
-${FSLDIR}/bin/imcp ${subjdir}/nodif_brain_mask ${subjdir}.bedpostX
-if [ `${FSLDIR}/bin/imtest ${subjdir}/nodif` = 1 ] ; then
-    ${FSLDIR}/bin/fslmaths ${subjdir}/nodif -mas ${subjdir}/nodif_brain_mask ${subjdir}.bedpostX/nodif_brain
+cp "${subjdir}/bvecs" "${subjdir}/bvals" "${subjdir}.bedpostX"
+"${FSLDIR}/bin/imcp" "${subjdir}/nodif_brain_mask" "${subjdir}.bedpostX"
+if [ $("${FSLDIR}/bin/imtest" "${subjdir}/nodif") = "1" ] ; then
+    "${FSLDIR}/bin/fslmaths" "${subjdir}/nodif" -mas "${subjdir}/nodif_brain_mask" "${subjdir}.bedpostX/nodif_brain"
 fi
 
 
 # Split the dataset in parts
-echo Pre-processing stage
+echo "Pre-processing stage"
 
 if [ ${gflag} -eq 1 ]; then
-	pre_command="$FSLDIR/bin/split_parts_gpu ${subjdir}/data ${subjdir}/nodif_brain_mask ${subjdir}.bedpostX/bvals ${subjdir}.bedpostX/bvecs ${subjdir}/grad_dev 1 $njobs ${subjdir}.bedpostX"
+    pre_command=("$FSLDIR/bin/split_parts_gpu" "${subjdir}/data" "${subjdir}/nodif_brain_mask" "${subjdir}.bedpostX/bvals" "${subjdir}.bedpostX/bvecs" "${subjdir}/grad_dev" 1 "$njobs" "${subjdir}.bedpostX")
 else
-	pre_command="$FSLDIR/bin/split_parts_gpu ${subjdir}/data ${subjdir}/nodif_brain_mask ${subjdir}.bedpostX/bvals ${subjdir}.bedpostX/bvecs NULL 0 $njobs ${subjdir}.bedpostX"
+    pre_command=("$FSLDIR/bin/split_parts_gpu" "${subjdir}/data" "${subjdir}/nodif_brain_mask" "${subjdir}.bedpostX/bvals" "${subjdir}.bedpostX/bvecs" NULL 0 "$njobs" "${subjdir}.bedpostX")
 fi
-if [ $qsys -eq 0 ]; then
-	#SGE
-	splitID=`${FSLDIR}/bin/fsl_sub -T 40 -l ${subjdir}.bedpostX/logs -N bedpostx_preproc_gpu $pre_command`
+if [ "$qsys" -eq 0 ]; then
+    #SGE
+    splitID=$("${FSLDIR}/bin/fsl_sub" -T 40 -l "${subjdir}.bedpostX/logs" -N bedpostx_preproc_gpu "${pre_command[@]}")
 else
-	#TORQUE
-	echo $pre_command > ${subjdir}.bedpostX/temp
-	torque_command="qsub -V $queue -l nodes=1:ppn=1:gpus=1,walltime=00:40:00 -N bedpostx_preproc_gpu -o ${subjdir}.bedpostX/logs -e ${subjdir}.bedpostX/logs"
-	splitID=`exec $torque_command ${subjdir}.bedpostX/temp | awk '{print $1}' | awk -F. '{print $1}'`
-        rm "${subjdir}.bedpostX/temp"
-	sleep 10
+    #TORQUE
+    echo "${pre_command[@]}" > "${subjdir}.bedpostX/temp"
+    torque_command=(qsub -V "$queue" -l "nodes=1:ppn=1:gpus=1,walltime=00:40:00" -N bedpostx_preproc_gpu -o "${subjdir}.bedpostX/logs" -e "${subjdir}.bedpostX/logs")
+    splitID=$(exec "${torque_command[@]}" "${subjdir}.bedpostX/temp" | awk '{print $1}' | awk -F. '{print $1}')
+    rm "${subjdir}.bedpostX/temp"
+    sleep 10
 fi
 
 
-nvox=`${FSLDIR}/bin/fslstats $subjdir.bedpostX/nodif_brain_mask -V  | cut -d ' ' -f1 `
+nvox=$("${FSLDIR}/bin/fslstats" "$subjdir.bedpostX/nodif_brain_mask" -V  | cut -d ' ' -f1)
 
-echo Queuing parallel processing stage
+echo "Queuing parallel processing stage"
 
-[ -f ${subjdir}.bedpostX/commands.txt ] && rm "${subjdir}.bedpostX/commands.txt"
+[ -f "${subjdir}.bedpostX/commands.txt" ] && rm "${subjdir}.bedpostX/commands.txt"
 
 monitor
 if ! "${FSLDIR}/bin/fsl_sub" --has_queues > /dev/null; then
-    ${subjdir}.bedpostX/monitor&
+    "${subjdir}.bedpostX/monitor" &
 fi
 
 part=0
-while [ $part -lt $njobs ]
+while [ $part -lt "$njobs" ]
 do
-    	partzp=`$FSLDIR/bin/zeropad $part 4`
+    partzp=$("$FSLDIR/bin/zeropad" $part 4)
 
-	if [ ${gflag} -eq 1 ]; then
-	    gopts="$opts --gradnonlin=${subjdir}.bedpostX/grad_dev_$part"
-	else
-	    gopts=$opts
-	fi
+    if [ ${gflag} -eq 1 ]; then
+        gopts=("${opts[@]}" "--gradnonlin=${subjdir}.bedpostX/grad_dev_$part")
+    else
+        gopts=("${opts[@]}")
+    fi
 
-	echo "${FSLDIR}/bin/xfibres_gpu --data=${subjdir}.bedpostX/data_$part --mask=$subjdir.bedpostX/nodif_brain_mask -b ${subjdir}.bedpostX/bvals -r ${subjdir}.bedpostX/bvecs --forcedir --logdir=$subjdir.bedpostX/diff_parts/data_part_$partzp $gopts ${subjdir} $part $njobs $nvox" >> ${subjdir}.bedpostX/commands.txt
+    xf_gpu=(\"${FSLDIR}/bin/xfibres_gpu\" --data=\"${subjdir}.bedpostX/data_$part\" --mask=\"$subjdir.bedpostX/nodif_brain_mask\" \
+        -b \"${subjdir}.bedpostX/bvals\" -r \"${subjdir}.bedpostX/bvecs\" --forcedir --logdir=\"$subjdir.bedpostX/diff_parts/data_part_$partzp\" \
+        "${gopts[@]}" "${subjdir}" "$part" "$njobs" "$nvox")
+    echo "${xf_gpu[@]}" >> "${subjdir}.bedpostX/commands.txt"
 
-    	part=$(($part + 1))
+    part=$((part + 1))
 done
 
-if [ $qsys -eq 0 ]; then
-	#SGE
-	bedpostid=`${FSLDIR}/bin/fsl_sub $queue -l ${subjdir}.bedpostX/logs -N bedpostx_gpu -j $splitID -t ${subjdir}.bedpostX/commands.txt`
+if [ "$qsys" -eq 0 ]; then
+    #SGE
+    bedpostid=$("${FSLDIR}/bin/fsl_sub" $queue -l "${subjdir}.bedpostX/logs" -N bedpostx_gpu -j "$splitID" -t "${subjdir}.bedpostX/commands.txt")
 else
-	#TORQUE
-	taskfile=${subjdir}.bedpostX/commands.txt
-	echo "command=\`cat "$taskfile" | head -\$PBS_ARRAYID | tail -1\` ; exec \$command" > ${subjdir}.bedpostX/temp
-	tasks=`wc -l $taskfile | awk '{print $1}'`
-	sge_tasks="-t 1-$tasks"
-	#PBS -t x-y: x and y are the array bounds
-	torque_command="qsub -V $queue -l nodes=1:ppn=1:gpus=1,walltime=3:00:00,pmem=16gb -N bedpostx_gpu -o ${subjdir}.bedpostX/logs -e ${subjdir}.bedpostX/logs -W depend=afterok:$splitID $sge_tasks"
-	bedpostid=`exec $torque_command ${subjdir}.bedpostX/temp | awk '{print $1}' | awk -F. '{print $1}'`
-        rm "${subjdir}.bedpostX/temp"
-	sleep 10
+    #TORQUE
+    taskfile=${subjdir}.bedpostX/commands.txt
+    echo "command=\$(cat \"$taskfile\" | head -\$PBS_ARRAYID | tail -1) ; exec \$command" > "${subjdir}.bedpostX/temp"
+    tasks=$(wc -l "$taskfile" | awk '{print $1}')
+    sge_tasks=(-t "1-$tasks")
+    #PBS -t x-y: x and y are the array bounds
+    torque_command=(qsub -V "$queue" -l "nodes=1:ppn=1:gpus=1,walltime=3:00:00,pmem=16gb" -N bedpostx_gpu -o "${subjdir}.bedpostX/logs" -e "${subjdir}.bedpostX/logs" -W "depend=afterok:$splitID" "${sge_tasks[@]}")
+    bedpostid=$(exec "${torque_command[@]}" "${subjdir}.bedpostX/temp" | awk '{print $1}' | awk -F. '{print $1}')
+    rm "${subjdir}.bedpostX/temp"
+    sleep 10
 fi
 
 
 echo Queuing post processing stage
-post_command="${FSLDIR}/bin/bedpostx_postproc_gpu.sh --data=${subjdir}/data --mask=$subjdir.bedpostX/nodif_brain_mask -b ${subjdir}.bedpostX/bvals -r ${subjdir}.bedpostX/bvecs  --forcedir --logdir=$subjdir.bedpostX/diff_parts $gopts $nvox $njobs ${subjdir} ${FSLDIR}"
-if [ $qsys -eq 0 ]; then
-	#SGE
-	mergeid=`${FSLDIR}/bin/fsl_sub -T 120 -j $bedpostid -N bedpostx_postproc_gpu -l ${subjdir}.bedpostX/logs $post_command`
+post_command=("${FSLDIR}/bin/bedpostx_postproc_gpu.sh" "--data=${subjdir}/data" "--mask=$subjdir.bedpostX/nodif_brain_mask" \
+    -b "${subjdir}.bedpostX/bvals" -r "${subjdir}.bedpostX/bvecs" --forcedir "--logdir=$subjdir.bedpostX/diff_parts" "${gopts[@]}" \
+    "$nvox" "$njobs" "${subjdir}" "${FSLDIR}")
+if [ "$qsys" -eq 0 ]; then
+    #SGE
+    mergeid=$("${FSLDIR}/bin/fsl_sub" -T 120 -j "$bedpostid" -N bedpostx_postproc_gpu -l "${subjdir}.bedpostX/logs" "${post_command[@]}")
 else
-	#TORQUE
-	echo $post_command > ${subjdir}.bedpostX/temp
-	torque_command="qsub -V $queue -l nodes=1:ppn=1:gpus=1,walltime=00:40:00 -N bedpostx_postproc_gpu -o ${subjdir}.bedpostX/logs -e ${subjdir}.bedpostX/logs -W depend=afterokarray:$bedpostid"
-	mergeid=`exec $torque_command ${subjdir}.bedpostX/temp | awk '{print $1}' | awk -F. '{print $1}'`
-        rm "${subjdir}.bedpostX/temp"
-	sleep 10
+    #TORQUE
+    echo "${post_command[@]}" > "${subjdir}.bedpostX/temp"
+    torque_command=(qsub -V "$queue" -l "nodes=1:ppn=1:gpus=1,walltime=00:40:00" -N bedpostx_postproc_gpu -o "${subjdir}.bedpostX/logs" -e "${subjdir}.bedpostX/logs" -W "depend=afterokarray:$bedpostid")
+    mergeid=$(exec "${torque_command[@]}" "${subjdir}.bedpostX/temp" | awk '{print $1}' | awk -F. '{print $1}')
+    rm "${subjdir}.bedpostX/temp"
+    sleep 10
 fi
 
-echo $mergeid > ${subjdir}.bedpostX/logs/postproc_ID
+echo "$mergeid" > "${subjdir}.bedpostX/logs/postproc_ID"
 
 if "${FSLDIR}/bin/fsl_sub" --has_queues >/dev/null; then
     echo
-    echo Type ${subjdir}.bedpostX/monitor to show progress.
-    echo Type ${subjdir}.bedpostX/cancel to terminate all the queued tasks.
-    cat <<EOC > ${subjdir}.bedpostX/cancel
+    echo "Type ${subjdir}.bedpostX/monitor to show progress."
+    echo "Type ${subjdir}.bedpostX/cancel to terminate all the queued tasks."
+    cat <<EOC > "${subjdir}.bedpostX/cancel"
 #!/bin/sh
 ${FSLDIR}/bin/fsl_sub --delete_job $mergeid
 ${FSLDIR}/bin/fsl_sub --delete_job $bedpostid
 EOC
-    chmod +x ${subjdir}.bedpostX/cancel
+    chmod +x "${subjdir}.bedpostX/cancel"
 
     echo
     echo
